name = "ryan-polasky-portfolio"
compatibility_date = "2025-08-26"

[env.production]
name = "ryan-polasky-portfolio"

# Static site configuration
pages_build_output_dir = "."

# Custom domain
# route = "ryanpolasky.com/*"

# Headers for security and performance
[[env.production.rules]]
type = "header"
src = "/*"
headers = { "X-Frame-Options" = "DENY", "X-Content-Type-Options" = "nosniff", "Referrer-Policy" = "strict-origin-when-cross-origin" }

[[env.production.rules]]
type = "header"
src = "*.html"
headers = { "Cache-Control" = "public, max-age=3600" }

[[env.production.rules]]
type = "header"
src = "*.css"
headers = { "Cache-Control" = "public, max-age=31536000" }

[[env.production.rules]]
type = "header"
src = "*.js"
headers = { "Cache-Control" = "public, max-age=31536000" }

[[env.production.rules]]
type = "header"
src = "*.png"
headers = { "Cache-Control" = "public, max-age=31536000" }

[[env.production.rules]]
type = "header"
src = "*.jpg"
headers = { "Cache-Control" = "public, max-age=31536000" }

[[env.production.rules]]
type = "header"
src = "*.ico"
headers = { "Cache-Control" = "public, max-age=31536000" }

[[env.production.rules]]
type = "header"
src = "*.pdf"
headers = { "Cache-Control" = "public, max-age=86400" }

[assets]
directory = "./ryanpolasky-website